### ISSUE TITLE
Editing Tasks

### ISSUE THREAD

**Issue by xuche123** [AY2021S1-CS2113T-F14-4/tp#30]
Created command to edit tasks

**Comment by Lee-Juntong** [comment]
syntax inferred:
edit *index*
the new event is entered with the same syntax as adding a new event.e.g. `assignment xxx /t 2020-10-01 20:00 /l somewhere

**Comment by Lee-Juntong** [comment]
in a later version, we shall allow the user to edit only one part of the event. i.e. only time or location or type or description
